# -*- coding: utf-8 -*-
"""PolinômioDeNewton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojZJe__s90wqbdPobwl1iOrMfEr-Q8TU
"""

import numpy as np
import matplotlib.pyplot as plt

# Função para calcular os coeficientes do polinômio de Newton
def coeficiente_newton(x, y):
    n = len(x)
    coef = np.zeros(n)
    for j in range(n):
        coef[j] = y[j]
        for k in range(1, n):
            for j in range(n - 1, k - 1, -1):
                coef[j] = (coef[j] - coef[j - 1]) / (x[j] - x[j - k])
    return coef

# Entrada de dados pelo usuario
n = int(input('Digite a quantidade de pontos: '))
x = np.zeros(n)
y = np.zeros(n)

for i in range(n):
    x[i] = float(input('Digite a coordenada x do ponto %d: ' % (i + 1)))
    y[i] = float(input('Digite a coordenada y do ponto %d: ' % (i + 1)))

# Calculo do Polinômio de Newton
p = coeficiente_newton(x, y)
print("Os coeficientes do polinômio de Newton são: ")
print(p)